config/routes.rb
Rails.application.routes.draw do
  resources :djs_gears

  resources :gears

  mount Commontator::Engine => '/commontator'
  devise_for :users    
  resources :djs
  resources :users
  resources :djsgear
  root 'static_page#home'
  get 'about' => 'static_page#about'
  get 'contact' => 'static_page#contact'
  get 'dj' => 'djs#index'
  get 'djresult' => 'djs#result'
  get 'gearresult' => 'gears#result'
  get 'allresult' => 'djs#resultall'
  get 'djgear' => 'djs#djgear', as: :djgear
  get 'user/:id/remove_photo', 
    to: 'users#remove_photo', 
    as: 'remove_user_photo'
  get 'dj/:id/remove_photo', 
    to: 'djs#remove_photo', 
    as: 'remove_dj_photo'  
  get 'gear/:id/remove_photo', 
    to: 'gears#remove_photo', 
    as: 'remove_gear_photo'  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  	has_attached_file :avatar, :styles => { 
  		:medium => "300x300>",
  		:small => "140x140", 
  		:thumb => "100x100>" }, 
  		:default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, 
  	:content_type => /\Aimage\/.*\Z/
     
	acts_as_commontator

	
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    # super do |resource|
    #   BackgroundWorker.trigger(resource)
    # end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_photo
    @user = User.find(params[:id])
    @user.avatar = nil
    @user.save
    redirect_to @user, flash: { success: 'User profile photo has been removed.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit( :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html:{ multipart:true} do |f| %>
  


    <%= f.label :avatar %>
    <%= f.file_field :avatar, html:{class: 'center'} %>
    <% if f.object.avatar? %>
    <br />
    <%= image_tag(f.object.avatar.url(:small)) %><br />
    <em>Currently uploaded image</em>
    <p>
      <%= f.object.avatar_file_name %>
    </p>
    <% if @user.persisted? %>
    <%= link_to 'Remove profile photo', remove_user_photo_path %>
    <% end %>
    <% end %>

  
  <div class="actions">
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>


  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
 </div>

app/views/users/edit.html.erb
<% if current_user.id == @user.id%>
<div class="row" style="margin-top:50px">
	<div class="col-md-4"></div>
  		<div class="col-md-6">
			<div class="input-group">
  				<div class = "panel panel-info">
  					<div class="panel-heading">
        				<h3 class="panel-title">Your Profile</h3>
      					<br>
					<!-- <p><h1>Your Profile</h1> <br /> -->
					Your current email: <%= @user.email %></p>
					</div>
						<div style="margin:10px">
							<%= link_to "Change your password or email", edit_user_registration_path ,class:"btn btn-default"%>
									<br />
							<%= render 'users/form'%>
						</div>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
				</div>
			</div>
		</div>
</div>


<% else %>

<h1> YOU CANNOT EDIT OTHER USER'S PROFILE </h1>

<% end %>

app/views/users/index.html.erb
<% if user_signed_in? && current_user.id == 1 %>


<div class"container" style="margin-top:50px">
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class = "table">
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to image_tag(user.avatar.url(:thumb), class: "img-thumbnail"),user %></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>



<% else %>
<h1>
YOU ARE NOT ADMIN
</h1>
<%end%>

app/views/users/new.html.erb
<div class="row" style="margin-top:50px">
<div class="col-md-2"></div>
  <div class="col-md-8">
  	<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<div class="col-md-2"></div>

</div>

app/views/users/show.html.erb
<div class="row"style="margin-top:50px">
<div class="col-md-4"></div>
  <div class="col-md-6 jumbotron">

<p id="notice"><%= notice %></p>


<div>
<%= image_tag @user.avatar.url(:medium), class: "img-thumbnail" %>
</div>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<% if current_user.id == @user.id %>
<%= link_to 'Edit', edit_user_path(@user) %> 
<% else %>

<% end %>
</div>
</div>