config/routes.rb
Rails.application.routes.draw do
  resources :djs_gears

  resources :gears

  mount Commontator::Engine => '/commontator'
  devise_for :users    
  resources :djs
  resources :users
  resources :djsgear
  root 'static_page#home'
  get 'about' => 'static_page#about'
  get 'contact' => 'static_page#contact'
  get 'dj' => 'djs#index'
  get 'djresult' => 'djs#result'
  get 'gearresult' => 'gears#result'
  get 'allresult' => 'djs#resultall'
  get 'djgear' => 'djs#djgear', as: :djgear
  get 'user/:id/remove_photo', 
    to: 'users#remove_photo', 
    as: 'remove_user_photo'
  get 'dj/:id/remove_photo', 
    to: 'djs#remove_photo', 
    as: 'remove_dj_photo'  
  get 'gear/:id/remove_photo', 
    to: 'gears#remove_photo', 
    as: 'remove_gear_photo'  
  

  

end

app/models/dj.rb
class Dj < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true, :length => {:maximum => 100 }
	require 'will_paginate/array'
	has_many :djs_gears
	has_many :gears, through: :djs_gears
	has_attached_file :avatar, :styles => { 
      :medium => "300x300>",
  		:small => "140x140", 
  		:thumb => "100x100>" }, 
  		:default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, 
  	:content_type => /\Aimage\/.*\Z/


	acts_as_commontable
 
 #  validates :title, presence: true, uniqueness: true
 #  validates :content, presence: true
 
  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
  end
  # self.per_page = 10
end

app/controllers/djs_controller.rb
class DjsController < ApplicationController
  before_action :set_dj, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:update,:destroy,:create,:edit]

  # GET /djs
  # GET /djs.json
  def index
    # @djs = Dj.all
    # WillPaginate.per_page = 10
    # @djs = Dj.paginate(:page => params[:page])
    
    @djs = Dj.paginate(:page => params[:page], :per_page => 12)

    

  end
  # GET /djresult
  def result
    if params[:search]
      @djs = Dj.search(params[:search]).order("created_at DESC")
      @gears = Gear.search(params[:search]).order("created_at DESC")
    else
      @djs = Dj.order("created_at DESC")
    end
  end
  
  def resultall
    if params[:search]
      @djs = Dj.search(params[:search]).order("created_at DESC")
      @gears = Gear.search(params[:search]).order("created_at DESC")
    else
      @djs = Dj.order("created_at DESC")
    end
  end

  def remove_photo
    @dj = Dj.find(params[:id])
    @dj.avatar = nil
    @dj.save
    redirect_to @dj, flash: { success: 'DJ profile photo has been removed.' }
  end


  # GET /djs/1
  # GET /djs/1.json
  def show
    commontator_thread_show(@dj)
    @gears = Gear.all
  end

  # def djgear
  #   @gears = Gear.all 
  #   @dj = Dj.find(params[:dj_id].to_i)
  # end

  

  # GET /djs/new
  def new
    @dj = Dj.new
  end

  # GET /djs/1/edit
  def edit
  end

  # POST /djs
  # POST /djs.json
  def create
    @dj = Dj.new(dj_params)

    respond_to do |format|
      if @dj.save
        format.html { redirect_to @dj, notice: 'Dj was successfully created.' }
        format.json { render :show, status: :created, location: @dj }
      else
        format.html { render :new }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /djs/1
  # PATCH/PUT /djs/1.json
  def update
    respond_to do |format|
      if @dj.update(dj_params)
        format.html { redirect_to @dj, notice: 'Dj was successfully updated.' }
        format.json { render :show, status: :ok, location: @dj }
      else
        format.html { render :edit }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /djs/1
  # DELETE /djs/1.json
  def destroy
    @dj.destroy
    respond_to do |format|
      format.html { redirect_to djs_url, notice: 'Dj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_admin
      raise "not admin" if current_user.id != 1
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_dj
      @dj = Dj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dj_params
      params.require(:dj).permit(:name, :description, :genre, :avatar)
    end
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/views/djs/_form.html.erb
<% if user_signed_in? && current_user.id == 1 %>
<%= simple_form_for(@dj)  do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true , class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre,class:"form-control"%>
  </div>  

  
  <div class="container">
  <%= f.label :DJ_picture %>
    <%= f.file_field :avatar, html:{class: 'center'} %>
  <% if f.object.avatar? %>
    <br/>
    <%= image_tag(f.object.avatar.url(:small)) %><br />
    <em>Currently uploaded image</em>
    <p><%= f.object.avatar_file_name %></p>
    <%= link_to 'Remove profile photo', remove_dj_photo_path %><br>
  <% end %>
  </div>


  <div class="form-actions ">
    <%= f.button :submit, class:"btn btn-success col-sm-12" %>
  </div>
  <%= f.error_notification %>

<% end %>




<% else %> 
<h1> YOU ARE NOT ADMIN </h1>
<% end %>

app/views/djs/djgear.html.erb
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-3">
<div  class="dropdown" style="margin-top:100px">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Dropdown
    <span class="caret"></span>
  </button>
<ul class="dropdown-menu">
    // showing a dj here
  </ul>
</div>
</div>


<div class="col-md-3">
<div  class="dropdown" style="margin-top:100px">  
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Dropdown
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <%  @gears.each do |gear| %>
      <a href=<%= gear_path(gear)%> class="list-group-item list-group-item-info" role="menuitem">
        <%= gear.name %></a>
  <% end %>
  </ul>
</div>
</div>

<div class="col-md-3"></div>


</div>

app/views/djs/edit.html.erb
<div class="row" style="margin-top:50px">
<div class="col-md-2"></div>
  <div class="col-md-8">
  	<h1>Editing Dj</h1>

		<%= render 'form' %>

<!--<%= link_to 'Show', @dj %> |
<%= link_to 'Back', djs_path %>-->

<div class="col-md-2"></div>

</div>

app/views/djs/index.html.erb
<div class="jumbotron "style="margin-top:70px">

    <div style="">
    <% if user_signed_in? %>
    <a href = <%=new_dj_path%>><button class = "btn btn-success btn-lg" >Add New Dj</button>
    </a>
    <% else %>
        <p> Log in to submit a Dj!!</p>
    <% end %>
    </div>

    <!-- DJS -->
<div class="container" style="margin: 10px">
    <div class="page-header">
        <h2> DJs </h2>
    </div>
    
<!-- gallery -->
    <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix" >
        <%  @djs.each do |dj| %>
        <!-- column -->
        <div class= "box col2">
            <div class="">
            <a href = <%=dj_path(dj)%>>
            <%= image_tag dj.avatar.url(:medium),class:"img-responsive img-rounded", style: "margin-bottom:10px" %>
            </a>
            <div class="caption">
            <h3>
            <%= link_to dj.name, dj_path(dj) %>
            </h3>
        </div>
    </div>
          </div>
        <% end %>
    </div>



</div>
<!-- DJs -->
    
    <div class="apple_pagination">
        <div class="page_info">
          <%= page_entries_info @djs %>
        </div>
        <%= will_paginate @djs%>
    </div>


</div>

app/views/djs/new.html.erb
<div class="row" style="margin-top:50px">
<div class="col-md-2"></div>
  <div class="col-md-8">
  	<div class="">

<h1>New Dj</h1>

<%= render 'form' %>

<!--<%= link_to 'Back', djs_path %>-->
</div>
<div class="col-md-2"></div>

</div>

app/views/djs/result.html.erb
<div class="center jumbotron" style="margin-top:50px">
    <h1>Search Result</h1> 

    <!-- row -->
    <div class = "container row">
        <div class="clearfix visible-xs-block"></div>
        <%  @djs.each do |dj| %>
        <!-- column -->        
        <div class= "col-xs-6 col-sm-2">
            <a href = <%=dj_path(dj)%>>
            <%= image_tag dj.avatar.url(:medium),class:"img-responsive img-rounded" %>
            
            <div class="caption">
                <h3>
                <%= link_to dj.name, dj_path(dj) %>
                </h3>
                
            </div>
            </a>
          </div>
        <% end %>
    </div>

app/views/djs/resultall.html.erb
<div class="center jumbotron" style="margin-top:50px">
    <h1>Search Result for Dj</h1> 

    <!-- row -->
    <div class = "container row">
        <div class="clearfix visible-xs-block"></div>
        <%  @djs.each do |dj| %>
        <!-- column -->        
        <div class= "col-xs-6 col-sm-2">
            <a href = <%=dj_path(dj)%>>
            <%= image_tag dj.avatar.url(:medium),class:"img-responsive img-rounded" %>
            
            <div class="caption">
                <h3>
                <%= link_to dj.name, dj_path(dj) %>
                </h3>
                
            </div>
            </a>
          </div>
        <% end %>
    </div>
    </div>

<div class="center jumbotron" style="margin-top:50px">
    <h1>Search Result for Gear</h1> 

    <!-- row -->
    <div class = "container row">
        <div class="clearfix visible-xs-block"></div>
        <%  @gears.each do |gear| %>
        <!-- column -->        
        <div class= "col-xs-6 col-sm-2">
            <a href = <%=gear_path(gear)%>>
            <%= image_tag gear.avatar.url(:medium),class:"img-responsive img-rounded" %>
            
            <div class="caption">
                <h3>
                <%= link_to gear.name, gear_path(gear) %>
                </h3>
                
            </div>
            </a>
          </div>
        <% end %>
    </div>
    </div>

app/views/djs/show.html.erb
<div class="well bs-component">
<div class=" col-md-12"><!-- Profile -->
  <div class="col-md-4">
    <div>
      <%= image_tag @dj.avatar.url(:medium),class:"img-responsive img-rounded" %>
    </div>
  </div>
  <div class="col-md-6">
    <p id="notice"><%= notice %></p>
    <h1>
      <strong>
      <%= @dj.name %>
      </strong>
    </h1>
    <h3>
      <strong>Bio:</strong>
    </h3>
    <h4>
      <%= @dj.description %>
    </h4>
    <p>
      <strong>Genre:</strong>
      <%= @dj.genre %>
    </p>
    <% if user_signed_in? && current_user.id == 1 %>
    	<%= link_to 'Destroy', @dj, method: :delete, data: { confirm: 'Are you sure?' } %>
    	<%= link_to 'Improve This Page!', edit_dj_path(@dj) %>
    <% else %>
    <% end %>
  </div>
  <div class="col-md-2"></div>
</div><!-- End of Profile -->
<!-- DjsGear -->
<div class = " col-sm-12">
      <div class="page-header">
        <h3>Gears <strong><%= @dj.name %></strong> Use:</h3><br>
        <% if user_signed_in? && current_user.id == 1 %>
        <a href=<%= new_djs_gear_path(dj_id: @dj)%> class="btn btn-success" role="button">Submit a gear the <%=@dj.name%> use</a>
        <%else%>
        <%end%>
      </div>
  <% if @dj.gears.count == 0 %>
    <p> This DJ have no recorded gear. </p>
  <%else%>
  <% @dj.gears.each do |gear| %>
    <div class= "col-xs-12 col-sm-2">
      <a href = <%=gear_path(gear)%>>
        <%= image_tag gear.avatar.url(:thumb),class:"img-responsive img-rounded " %>
      </a>
      <div class="caption">
      <h4>
        <%= link_to gear.name, gear_path(gear) %>
      </h4>
      </div>
    </div>
<% end %>
<% end %>
</div>
<!-- End of DjsGear -->
<!-- Comment Section -->
<div class = "">
  <div class="page-header">
    <h3> <strong>Comments</strong> on this DJ</h3>
  </div>
  <%= commontator_thread(@dj) %>
</div>
</div><!-- Container -->