config/routes.rb
Rails.application.routes.draw do
  resources :djs_gears

  resources :gears

  mount Commontator::Engine => '/commontator'
  devise_for :users    
  resources :djs
  resources :users
  resources :djsgear
  root 'static_page#home'
  get 'about' => 'static_page#about'
  get 'contact' => 'static_page#contact'
  get 'dj' => 'djs#index'
  get 'djresult' => 'djs#result'
  get 'gearresult' => 'gears#result'
  get 'allresult' => 'djs#resultall'
  get 'djgear' => 'djs#djgear', as: :djgear
  get 'user/:id/remove_photo', 
    to: 'users#remove_photo', 
    as: 'remove_user_photo'
  get 'dj/:id/remove_photo', 
    to: 'djs#remove_photo', 
    as: 'remove_dj_photo'  
  get 'gear/:id/remove_photo', 
    to: 'gears#remove_photo', 
    as: 'remove_gear_photo'  
  

  

end

app/models/gear.rb
class Gear < ActiveRecord::Base
	validates :name, presence: true,uniqueness: true
	has_many :djs_gears
	has_many :djs, through: :djs_gears
	belongs_to :geartype
	# has_and_belongs_to_many :djs, :join_table => "djs_gears"
	has_attached_file :avatar, :styles => { 
	  	:medium => "300x300>", 
	  	:small => "140x140",
	  	:thumb => "100x100>" }, 
	  	:default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, 
  	:content_type => /\Aimage\/.*\Z/
  	acts_as_commontable

  	def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
    @gears = Gear.all
  end

   def result
    if params[:search]
      @gears = Gear.search(params[:search]).order("created_at DESC")
    else
      @gears = Gear.order("created_at DESC")
    end
  end


  # GET /gears/new
  def new
    @gear = Gear.new
  end

  # GET /gears/1/edit
  def edit
    
  end

  def remove_photo
    @gear = Gear.find(params[:id])
    @gear.avatar = nil
    @gear.save
    redirect_to @gear, flash: { success: 'Gear profile photo has been removed.' }
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        # raise "#{params}" 
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear
      @gear = Gear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_params
      params.require(:gear).permit(:name, :description, :geartype_id, :dj_id, :avatar, :buylink, :geartype_name)
    end
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/gears/_form.html.erb
<% if user_signed_in? && current_user.id == 1 %>

<%= simple_form_for(@gear) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true , class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control"%>  
  </div>
  <div class="field">
    <%= f.label :buy_link %>
    <%= f.text_field :buylink, class:"form-control"%>  
  </div>




   <%= f.label :gear_picture %>
    <%= f.file_field :avatar, html:{class: 'center'} %>
      <% if f.object.avatar? %>
      <br />
      <%= image_tag(f.object.avatar.url(:small)) %><br />
      <em>Currently uploaded image</em>
      <p><%= f.object.avatar_file_name %></p>
      <%= link_to 'Remove profile photo', remove_gear_photo_path %>
      
  <% end %>



<%= link_to 'Destroy', gear_path, method: :delete, data: { confirm: 'Are you sure?' } %>

  <div class="form-actions ">
    <%= f.button :submit, class:"btn btn-success col-sm-12" %>
  </div>
<% end %>

<% else %> 
<h1> YOU ARE NOT ADMIN </h1>
<% end %>

app/views/gears/edit.html.erb
<div class="row" style="margin-top:50px">
<div class="col-md-2"></div>
  <div class="col-md-8">
  	<h1>Editing Gear</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @gear %> |
<%= link_to 'Back', gears_path %>-->
<div class="col-md-2"></div>

</div>

app/views/gears/index.html.erb
<div class="jumbotron"style="margin-top:50px">

  <p id="notice"><%= notice %></p>

  <div style="">
    
    <% if user_signed_in? && current_user.id == 1%>
        <a href = <%=new_gear_path%>><button class = "btn btn-success btn-lg" >Add New Gear</button>
        </a>
    <% else %>
    <% end %>
    </div>

<!-- GEARS -->
<div class="" style="margin: 10px" >
  <div class="page-header">
        <h2> Gears </h2>
    </div>
<!-- row -->
    <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
        <%  @gears.each do |gear| %>
        <!-- column -->
        <div class= "box col3" >
        <div class= "">
          <a href = <%=gear_path(gear)%>>
            <%= image_tag gear.avatar.url(:medium),class:"img-responsive img-rounded ",style:"margin-buttom:10px" %>
            </a>
            <div class="caption">
            <h3>
            <%= link_to gear.name, gear_path(gear) %>
            </h3>
            <!-- <p>Description: <br><%=gear.description %></p> -->
        </div>
        </div>
    </div>
        <% end %>

    </div>

</div>
<!-- GEARS -->


<br>

    <div class="apple_pagination">
        <div class="page_info">
          <%= page_entries_info @gears %>
        </div>
        <%= will_paginate @gears%>
    </div>

</div>

app/views/gears/new.html.erb
<div class="row" style="margin-top:50px">
<div class="col-md-2"></div>
  <div class="col-md-8">
  	<h1>New Gear</h1>

<%= render 'form' %>

<!--<%= link_to 'Back', gears_path %>-->
<div class="col-md-2"></div>

</div>

app/views/gears/result.html.erb
<div class="center jumbotron" style="margin-top:50px">
    <h1>Search Result</h1> 

    <!-- row -->
    <div class = "container row">
        <div class="clearfix visible-xs-block"></div>
        <%  @gears.each do |gear| %>
        <!-- column -->        
        <div class= "col-xs-6 col-sm-2">
            <a href = <%=gear_path(gear)%>>
            <%= image_tag gear.avatar.url(:medium),class:"img-responsive img-rounded" %>
            
            <div class="caption">
                <h3>
                <%= link_to gear.name, gear_path(gear) %>
                </h3>
                
            </div>
            </a>
          </div>
        <% end %>
    </div>

app/views/gears/show.html.erb
<div class=" jumbotron">
<!-- Gear Profile -->
  <div class="row">
    <div class="col-md-4">
      <div>
        <%= image_tag @gear.avatar.url(:medium),class:"img-responsive img-rounded" %>
      </div>
    </div>
    <div class="col-md-6">
  	<p id="notice"><%= notice %></p>
    <p>
      <h1>
        <strong><%= @gear.name %></strong>
      </h1>
    </p>
    <h3>
      <strong>Description:</strong><br>
    </h3>
    <% if @gear.description.blank? %>
      <h4> No description available </h4>
    <% else %>
      <h4>
        <%= @gear.description %>
        <% end %>
      </h4>
    <% if @gear.buylink? %>
      <a href= <%=@gear.buylink%> class="btn btn-success" role="button" >Link to manufacturer's page</a>
    <%else%>
    <% end %>
    <% if user_signed_in? && current_user.id == 1 %>
      <a class = "btn btn-warning" role="button" href=<%=edit_gear_path(@gear)%>>Improve this page</a>
    <%else%>
    <%end%>
    </div>
      <div class="col-md-2"></div>
  </div>
<!-- End Gear Profile -->
<!-- GearsDj -->
<div class="col-md-12">
  <div class="page-header">
    <h3>Dj that use <strong><%= @gear.name %></strong></h3>
  </div>  
  <% if @gear.djs.count == 0 %>
    <p> We have no record of Dj that use this product. </p>
  <% else %>
  <% @gear.djs.each do |dj|%>
  <div class="col-xm-12 col-sm-2">
    <a href=<%=dj_path(dj)%>><%= image_tag dj.avatar.url(:thumb),class:"img-responsive img-rounded " %></a>
    <h3><%= link_to dj.name, dj_path(dj) %></h3><br>
  </div>
  <% end %>
  <% end %>
</div> 
<!-- End of GearsDj -->
<!-- Comments -->
<div>
  <div class="page-header">
    <h3> <strong>Comments</strong> on this Gear</h3>
  </div>
  <%= commontator_thread(@gear) %>
</div>
</div><!-- Container -->