config/routes.rb
Rails.application.routes.draw do
  resources :djs_gears

  resources :gears

  mount Commontator::Engine => '/commontator'
  devise_for :users    
  resources :djs
  resources :users
  resources :djsgear
  root 'static_page#home'
  get 'about' => 'static_page#about'
  get 'contact' => 'static_page#contact'
  get 'dj' => 'djs#index'
  get 'djresult' => 'djs#result'
  get 'gearresult' => 'gears#result'
  get 'allresult' => 'djs#resultall'
  get 'djgear' => 'djs#djgear', as: :djgear
  get 'user/:id/remove_photo', 
    to: 'users#remove_photo', 
    as: 'remove_user_photo'
  get 'dj/:id/remove_photo', 
    to: 'djs#remove_photo', 
    as: 'remove_dj_photo'  
  get 'gear/:id/remove_photo', 
    to: 'gears#remove_photo', 
    as: 'remove_gear_photo'  
  

  

end

app/views/layouts/_body.html.erb
<body>
	
      <%= render 'layouts/header' %>

      <div style="margin-top: 100px">
      	<%= yield %>
  	  </div>
      

     <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>-->


    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> 
    

  </body>

app/views/layouts/_footer.html.erb
<footer class="footer">
        <p>&copy; Supasit Tanapatpiboon 2015</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" >
  <nav class="navbar-inner " id="header-wrap"  >
  <div class="">
    <div class = "navbar-header">
      <button type="button" class="navbar-toggle collapsed"  data-toggle="collapse" data-target="#bs-example-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to "DJDatabase", root_path, class: "navbar-brand" %>
    </div>
      <div class=" collapse navbar-collapse " id="bs-example-navbar-collapse">
      <ul class=" nav navbar-nav">
            
            <li role="presentation">
              <%= link_to "Home", root_path %>
            </li>  
            <li role="presentation">
              <%= link_to "About", about_path %>
            </li>
            <li role="presentation">
              <%= link_to "Contact", contact_path %>
            </li>
            <li class="divider"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Library <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "DJs", djs_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Gears", gears_path %></li>
              </ul>
            </li>
            <% if user_signed_in? && current_user.id == 1 %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Submit<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "New DJs", new_dj_path %></li>
                <li class="divider"></li>
                <li><%= link_to "New Gears", new_gear_path %></li>
              </ul>
            </li>
            <% else %> 
            <% end %>
        <% if user_signed_in? %>
              <li class="divider"></li>
              <li>
                <li><%= link_to current_user.email, user_path(id: current_user.id) %></li>
              <li><%= link_to "Log Out",destroy_user_session_path, :method => :delete  %></li>
              </li>
        <% else %>
          <li class="divider"></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Create Account",new_user_registration_path %></li>
        <% end %>

      <li>
      <div id = "allsearch" class="navbar-right">
      <%= form_tag(allresult_path, :method => "get", class: " navbar-form navbar-right", role:"serach") do %>
        <div class="form-group">

          <%= text_field_tag :search, params[:search], style: "color:black", placeholder: "Search ..." %>
          <% end %>
        </div>
      </div>
    </li>

    </ul>

    </div>
  </div>
</nav>
</div>

app/views/layouts/_shim.html.erb
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DJDB&reg;</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script type="text/javascript" src="//twitter.github.io/bootstrap/assets/js/bootstrap-transition.js"></script>
    <script type="text/javascript" src="//twitter.github.io/bootstrap/assets/js/bootstrap-collapse.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>  
    
    

    <!-- <script src="assets/javascripts/masonry.pkgd.min.js"></script>-->

    <!-- <link rel="icon" href="../../favicon.ico"> -->
    <!-- <title>Narrow Jumbotron Template for Bootstrap</title> -->
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="jumbotron-narrow.css" rel="stylesheet"> -->
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->
    <%= render 'layouts/shim' %>
</head>

<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
<% end %>


  <div class="container">
	<%= render 'layouts/body' %>
  <%= render 'layouts/footer' %>
  </div>
  <!--<%= debug(params) if Rails.env.development? %>-->
  
</html>